# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastmenu',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastmenu',
                'lib_path': 'fastmenu'},
  'syms': {'fastmenu.core': {'fastmenu.core.foo': ('core.html#foo', 'fastmenu/core.py')}}}
